### Create a Request
POST http://localhost:8080/odata/v4/CustomerService/Requests
Content-Type: application/json

{
  "title": "Phí sinh hoạt hàng tháng của văn phòng.",
  "desc": "Tiền dien, tien nuoc, tien mang thang 03/2025 văn phòng Cũ",
  "status": "New",
  "urgent": false,
  "Bills": [
    {
      "title": "Tien dien",
      "category": "Office_M",
      "charge": 500000
    },
    {
      "title": "Tien nuoc",
      "category": "Office_M",
      "charge": 500000
    },
    {
      "title": "Tien mang",
      "category": "Office_M",
      "charge": 500000
    }
  ],
  "Comments": [
    {
      "content": "All information in this request is resonable, I accepted it."
    },
    {
      "content": "I repaid for Ahuy"
    },
    {
      "content": "The refund was sent to my account"
    }
  ]
}



### Create a Bill
POST http://localhost:8080/odata/v4/CustomerService/Bills
Content-Type: application/json

{
  "title": "Tiền vận chuyển",
  "category": "Others",
  "charge": 2000000.00,
  "request_ID": "25d9f5e1-1a73-41e9-b5c1-56e6ae4be2b3"
}


### Create a Comment
POST http://localhost:8080/odata/v4/CustomerService/Comments
Content-Type: application/json

{
  "content": "Yêu cầu xem lại hóa đơn.",
  "request_ID": "25d9f5e1-1a73-41e9-b5c1-56e6ae4be2b3"
}


### Below is the old version


### Retrieve Bill Information by ID
GET http://localhost:8080/odata/v4/CustomerService/Bills(ID=e2626401-bba4-4607-a690-ce8d715eca7e)?$expand=items





### Create items into a particular Bill

POST http://localhost:8080/odata/v4/CustomerService/Items
Content-Type: application/json

{
    "title": "nuoc ep",
      "category": "drink",
      "charge": 15.00,
      "amount": 1,
      "desc": "1 ly nuoc ep",
      "bill_ID": "e2626401-bba4-4607-a690-ce8d715eca7e"
}

### Update an Item

PATCH http://localhost:8080/odata/v4/CustomerService/Items(d575d489-7552-4469-b819-72847bbc960a)
Content-Type: application/json

{
      "title": "nuoc ep updated",
      "category": "drink",
      "charge": 15.00,
      "amount": 1,
      "desc": "1 ly nuoc ep updated",
      "bill_ID": "e2626401-bba4-4607-a690-ce8d715eca7e"
}

### Delete an Item
DELETE http://localhost:8080/odata/v4/CustomerService/Items(3a3839da-e824-4302-8609-c1f3c0cead04)




### Update a Bill

PATCH http://localhost:8080/odata/v4/CustomerService/Bills(e2626401-bba4-4607-a690-ce8d715eca7e)
Content-Type: application/json

{
  "title": "Updated Utility Payment",
  "sumCharge": 160.00,
  "desc": "Updated bill for utility charges.",
  "status": "PAID"
}

### Delete a bill 
DELETE http://localhost:8080/odata/v4/CustomerService/Bills(94e2d03f-8f1a-4a5e-84b7-28cbe3cf94f2)


